apiVersion: v1                                                                                                                                             
kind: Pod                                                                                                                                                
metadata:
  name: backend
spec:                                                                                                                                                      
  containers:
    - name: backend                                                                                                                                        
      image: ghcr.io/imakhankov/backend:latest                                                                                                           
      ports:                                                                                                                                               
        - containerPort: 5000